language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
script: 
  - pytest --cov=./
  - python taxsim
after_success:
  - codecov --token=f891d7ee-30bf-4c1c-b93b-643ea636c88c
notifications:
  slack: taxfoundation:kX1efSnT7Gwuh8nuKviECq3r